CREATE PROCEDURE [dbo].[Testing_SetupSystemConfig]

AS
BEGIN
-- Configure Seasons
INSERT INTO SystemConfig.Season (SeasonID, Year) VALUES (1, '2015')
INSERT INTO SystemConfig.Season (SeasonID, Year, StartDate, EndDate, CurrentSeason) VALUES (2, '2016', '4/3/2016', '9/25/2016', 1)

-- RosterPositions
INSERT INTO SystemConfig.RosterPositions (PositionID, CategoryType, Abbreviation, Description) VALUES (1,'B', 'C', 'Catcher')
INSERT INTO SystemConfig.RosterPositions (PositionID, CategoryType, Abbreviation, Description) VALUES (2,'B', '1B', 'First Basemen')
INSERT INTO SystemConfig.RosterPositions (PositionID, CategoryType, Abbreviation, Description) VALUES (3,'B', '2B', 'Second Basemen')
INSERT INTO SystemConfig.RosterPositions (PositionID, CategoryType, Abbreviation, Description) VALUES (4,'B', '3B', 'Third Basemen')
INSERT INTO SystemConfig.RosterPositions (PositionID, CategoryType, Abbreviation, Description) VALUES (5,'B', 'SS', 'Shortstop')
INSERT INTO SystemConfig.RosterPositions (PositionID, CategoryType, Abbreviation, Description) VALUES (6,'B', 'OF', 'Outfielder')
INSERT INTO SystemConfig.RosterPositions (PositionID, CategoryType, Abbreviation, Description) VALUES (7,'B', 'U', 'Utility')
INSERT INTO SystemConfig.RosterPositions (PositionID, CategoryType, Abbreviation, Description) VALUES (8,'P', 'SP', 'Starting Pitcher')
INSERT INTO SystemConfig.RosterPositions (PositionID, CategoryType, Abbreviation, Description) VALUES (9,'P', 'RP', 'Relief Pitcher')
INSERT INTO SystemConfig.RosterPositions (PositionID, CategoryType, Abbreviation, Description) VALUES (10,'P', 'P', 'Pitcher')
INSERT INTO SystemConfig.RosterPositions (PositionID, CategoryType, Abbreviation, Description) VALUES (11,'B', 'MI', 'Middle Infielder')
INSERT INTO SystemConfig.RosterPositions (PositionID, CategoryType, Abbreviation, Description) VALUES (12,'B', 'CI', 'Corner Infielder')
INSERT INTO SystemConfig.RosterPositions (PositionID, CategoryType, Abbreviation, Description) VALUES (13,'B', 'LF', 'Left Fielder')
INSERT INTO SystemConfig.RosterPositions (PositionID, CategoryType, Abbreviation, Description) VALUES (14,'B', 'CF', 'Center Fielder')
INSERT INTO SystemConfig.RosterPositions (PositionID, CategoryType, Abbreviation, Description) VALUES (15,'B', 'RF', 'Right Fielder')
INSERT INTO SystemConfig.RosterPositions (PositionID, CategoryType, Abbreviation, Description) VALUES (16,'B', 'DH', 'Designated Hitter')

-- Scoring Categories
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (1,'B', 'BA', 'Batting Average')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (2,'B', 'BB', 'Walks (Batters)')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (3,'B', 'H', 'Hits')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (4,'B', 'HR', 'Home Runs')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (5,'B', 'KO', 'Strikeouts (Batter)')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (6,'B', 'R', 'Runs')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (7,'B', 'RBI', 'Runs Batted In')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (8,'B', 'SB', 'Stolen Bases')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (9,'B', 'SLG', 'Slugging Pct')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (10,'B', '1B', 'Singles')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (11,'B', '2B', 'Doubles')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (12,'B', '3B', 'Triples')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (13,'B', 'AB', 'At Bats')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (14,'B', 'ABRISP', 'AtBat Runners in Sco. Pos.')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (15,'B', 'AST', 'Assists')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (16,'B', 'BP', 'Bases Produced')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (17,'B', 'BPA', 'Plate Appearances (Batter)')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (18,'B', 'CI', 'Catcher Interference')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (19,'B', 'COM', 'Combo')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (20,'B', 'CS', 'Caught Stealing')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (21,'B', 'CSC', 'Caught Stealing by Catcher')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (22,'B', 'CYC', 'Hitting for the Cycle')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (23,'B', 'DPT', 'Double Plays Turned')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (24,'B', 'DT', 'Doubles Plus Triples')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (25,'B', 'E', 'Errors')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (26,'B', 'FC', 'Fielding Chances')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (27,'B', 'FPCT', 'Fielding Pct')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (28,'B', 'G', 'Games')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (29,'B', 'GDP', 'Ground Into Double Plays')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (30,'B', 'GSHR', 'Grand Slam Home Runs')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (31,'B', 'GST', 'Games Started (Batter)')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (32,'B', 'HP', 'Hit by Pitch')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (33,'B', 'HRISP', 'Hits Runners in Sco. Pos.')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (34,'B', 'IB', 'Intentional Walks')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (35,'B', 'LOB', 'Left On Base')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (36,'B', 'OBP', 'On Base Pct')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (37,'B', 'OFAST', 'OF Assists')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (38,'B', 'OPS', 'On Base plus Slugging Pct')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (39,'B', 'PBC', 'Passed Balls by Catcher')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (40,'B', 'PKOF', 'Pick Offs by Fielder')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (41,'B', 'PO', 'Put Outs')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (42,'B', 'PP', 'Production Pct')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (43,'B', 'RBI-HR', 'RBI Minus Home Runs')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (44,'B', 'RP', 'Runs Produced')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (45,'B', 'RPA', 'Runs Produced Average')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (46,'B', 'RdAB', 'Runs per At Bat')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (47,'B', 'SB-CS', 'Stolen Bases - Caught Stealing')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (48,'B', 'SBA', 'Stolen Bases Allowed')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (49,'B', 'SBPCT', 'Stolen Base Pct')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (50,'B', 'SDT', 'Singles + Doubles + Triples')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (51,'B', 'SF', 'Sacrifice Flies')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (52,'B', 'SH', 'Sacrifice Hits')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (53,'B', 'TB', 'Total Bases')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (54,'B', 'TPA', 'Total Pct Average')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (55,'B', 'TPT', 'Triple Plays Turned')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (56,'B', 'XBH', 'Extra Base Hits')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (57,'P', 'BAA', 'Batting Average Against')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (58,'P', 'ERA', 'Earned Run Average')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (59,'P', 'INN', 'Innings')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (60,'P', 'K', 'Strikeouts (Pitcher)')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (61,'P', 'Kd9', 'Strikeouts per Nine')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (62,'P', 'QS', 'Quality Starts')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (63,'P', 'S+HD', 'Saves plus Holds')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (64,'P', 'W', 'Wins')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (65,'P', 'WHIP', 'Walks + Hits / Inning')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (66,'P', '1BA', 'Singles Allowed')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (67,'P', '2BA', 'Doubles Allowed')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (68,'P', '3BA', 'Triples Allowed')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (69,'P', 'ABA', 'At Bats Against')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (70,'P', 'AO', 'Air Outs')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (71,'P', 'APP', 'Appearances')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (72,'P', 'B', 'Balks')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (73,'P', 'BBI', 'Walks Issued (Pitchers)')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (74,'P', 'BBd9', 'Walks per Nine')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (75,'P', 'BFP', 'Batters Facing Pitcher')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (76,'P', 'BS', 'Blown Saves')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (77,'P', 'BSL', 'Blown Save Losses')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (78,'P', 'CG', 'Complete Games')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (79,'P', 'CGL', 'Complete Game Loss')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (80,'P', 'ER', 'Earned Runs')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (81,'P', 'GF', 'Games Finished')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (82,'P', 'GO', 'Ground Outs')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (83,'P', 'GS', 'Games Started (Pitcher)')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (84,'P', 'GdAO', 'Ground Outs/Air Outs')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (85,'P', 'HA', 'Hits Allowed')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (86,'P', 'HB', 'Hit Batsmen')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (87,'P', 'HD', 'Holds')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (88,'P', 'HIP', 'Hits per Inning')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (89,'P', 'HRA', 'Home Runs Allowed')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (90,'P', 'Hd9', 'Hits per Nine')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (91,'P', 'IBBI', 'Intentional Walks')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (92,'P', 'INNdGS', 'Innings per Start')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (93,'P', 'IRS', 'Inherited Runners Scored')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (94,'P', 'K-BB', 'Strikeouts Minus Walks')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (95,'P', 'L', 'Losses')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (96,'P', 'MERA', 'Modified ERA')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (97,'P', 'NH', 'No-Hitters')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (98,'P', 'NHL', 'No-Hitter Loss')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (99,'P', 'NW', 'Net Wins')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (100,'P', 'OBA', 'On Base Pct Against')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (101,'P', 'OUTS', 'Outs')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (102,'P', 'PA', 'Plate Appearances')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (103,'P', 'PC', 'Pitch Count')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (104,'P', 'PG', 'Perfect Games')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (105,'P', 'PKO', 'Pick Offs')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (106,'P', 'RA', 'Runs Allowed')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (107,'P', 'RL', 'Relief Losses')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (108,'P', 'RW', 'Relief Wins')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (109,'P', 'Rd9', 'Men on Base/ 9 Innings')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (110,'P', 'S', 'Saves')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (111,'P', 'SO', 'Shutouts')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (112,'P', 'SOP', 'Save Opportunities')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (113,'P', 'TBA', 'Total Bases Allowed')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (114,'P', 'W-L', 'Wins Minus Losses')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (115,'P', 'WP', 'Wild Pitches')
INSERT INTO SystemConfig.ScoringCategories (CategoryID, CategoryType, Abbreviation, Description) VALUES (116,'P', 'WPCT', 'Winning Pct')

END