//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cash_Receipt_Transaction
    {
        public int CashID { get; set; }
        public int InvoiceID { get; set; }
        public int UserID { get; set; }
        public System.DateTime Receipt_Date { get; set; }
        public decimal Amount { get; set; }
        public string Deposit_Number { get; set; }
        public string Record_Status { get; set; }
        public System.DateTime Date_Time_Created { get; set; }
        public string User_Id_Created { get; set; }
        public System.DateTime Date_Time_Modified { get; set; }
        public string User_Id_Modified { get; set; }
        public string Form_Id { get; set; }
    }
}
