//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<bool> ReceiveNewsletter { get; set; }
        public System.DateTime Date_Time_Created { get; set; }
        public string User_Id_Created { get; set; }
        public System.DateTime Date_Time_Modified { get; set; }
        public string User_Id_Modified { get; set; }
        public string Form_Id { get; set; }
    }
}
